### ISSUE TITLE
error

### ISSUE THREAD

**Issue by motaher90** [dapi-co/dapi-php#4]
I got this error while create a new object from dapi
{
    "message": "main(): Failed opening required 'vendor/autoload.php' (include_path='C:\\xampp-7.4.28\\php\\PEAR')",
    "exception": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
    "file": "D:\\Mine\\Qashi\\Full-Time\\projects\\NEW\\qashi-b2c-backend\\vendor\\dapi-co\\dapi-php\\src\\DapiClient.php",
    "line": 13,
    "trace": []
}

and when I comment line 13 [require_once 'vendor/autoload.php';] on DapiClient.php its working successfully

**Comment by navyasuri** [comment]
Hi @motaher90 - Apologies for the delayed response. 
For us to understand further, could please provide the following details?
1. Composer version
2. PHP version
3. Framework used (with version(s))

In addition, please try the following fixes
1. Double check you have already run `composer install` after you did `composer require dapi-co/dapi-php` or added the `dapi-php` library to your `composer.json` file.
2. If the above did not fix your issues, please run `composer update dapi-co/dapi-php`
3. If you still have issues, try cleaning up the dependencies by running `composer dump-autoload`

If you still get issues, please share the errors again.

**Comment by motaher90** [comment]
Dears,

I tried all fixes you told me but I had same issue.

here are details you want to know:-

  1.  Composer version
Composer version 2.0.13
  2.  PHP version
PHP 7.4.28
  3.  Framework used (with version(s))
Laravel Framework 8.83.18

Thanks and Regars

________________________________

**Comment by navyasuri** [comment]
Hi again @motaher90 
We have tested the library with multiple different frameworks and environments. Unfortunately, we are unable to replicate the issue. As a last resort, I would suggest trying with a clean environment to see if this issue occurs again. Make sure to run `composer install` after adding the library to your `composer.json`.
In addition, please reach out to support@dapi.com to schedule a call for us to go over it in more detail.

**Comment by navyasuri** [comment]
Hi @motaher90, we are closing this request. Please reach out to support@dapi.com if you are still facing issues!
